export const motivationalQuotes = [
  "The only way to do great work is to love what you do. - Steve Jobs",
  "Code is like humor. When you have to explain it, it's bad. - Cory House",
  "First, solve the problem. Then, write the code. - John Johnson",
  "Experience is the name everyone gives to their mistakes. - Oscar Wilde",
  "The best error message is the one that never shows up. - Thomas Fuchs",
  "Programs must be written for people to read, and only incidentally for machines to execute. - Harold Abelson",
  "Talk is cheap. Show me the code. - Linus Torvalds",
  "Any fool can write code that a computer can understand. Good programmers write code that humans can understand. - Martin Fowler",
  "Simplicity is the soul of efficiency. - Austin Freeman",
  "Sometimes it pays to stay in bed on Monday, rather than spending the rest of the week debugging Monday’s code. - Dan Salomon",
  "Before software can be reusable it first has to be usable. - Ralph Johnson",
  "Truth can only be found in one place: the code. - Robert C. Martin",
  "In order to be irreplaceable, one must always be different. - Coco Chanel",
  "Knowledge is power. - Francis Bacon",
  "Testing leads to failure, and failure leads to understanding. - Burt Rutan",
  "Perfection is achieved, not when there is nothing more to add, but when there is nothing left to take away. - Antoine de Saint-Exupery",
  "A good programmer is someone who always looks both ways before crossing a one-way street. - Doug Linder",
  "Fix the cause, not the symptom. - Steve Maguire",
  "Optimism is an occupational hazard of programming: feedback is the treatment. - Kent Beck",
  "It's not a bug – it's an undocumented feature. - Anonymous",
  "Any sufficiently advanced bug is indistinguishable from a feature. - Rich Kulawiec",
  "Programming isn't about what you know; it's about what you can figure out. - Chris Pine",
  "The function of good software is to make the complex appear to be simple. - Grady Booch",
  "Code never lies, comments sometimes do. - Ron Jeffries",
  "The most damaging phrase in the language is: ‘We’ve always done it this way.’ - Grace Hopper",
];
